spring:
  application:
    name: rideshare

  data:
    mongodb:
      uri: mongodb://localhost:27017/rideshare

  profiles:
    active: local

  data:
    redis:
      host: localhost
      port: 6379